### ISSUE TITLE
 WARNING  failed to contact turbod.

### ISSUE THREAD

**Issue by AddictArts** [vercel/turbo#2034]
### What version of Turborepo are you using?

1.5.1

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

After upgrading from 1.4.7 I now get a warning. Following the warning text leads to not a fix. The log is fine and I've removed the temp files, no fix.

### Expected Behavior

No warning or turbod properly launching. If a warning must be shown, it should reflect failure to launch turbod, not contact it.

### To Reproduce

Upgrade a 1.4.7 to 1.5.1

**Comment by nathanhammond** [comment]
In 1.5 we have toggled on using the daemon by default. On your machine the connection between the main turbo process and the daemon is failing.

This does not prevent your build from running to completion but we do need to identify why that connection is failing.

- Can you tell me more about your OS?
- Can you identify if you have write permissions to the path generated here? https://github.com/vercel/turborepo/blob/0dfa8e681c64a2bba9e8227d349b87f2f4bf7d04/cli/internal/daemon/daemon.go#L47 (we need better logging here to make this easier, you'd need to identify where Golang tempdir is creating a folder)
- what permissions does your user have?￼

**Comment by AddictArts** [comment]
@nathanhammond  Thanks for the reply. How do you even start the daemon? I searched the docs and only the cache config mentions a daemon. I understand the principle, but I just upgraded, didn't make a change to turbo.json to run a daemon. Is this something like Gradle where it spins it up on first launch? Just wanted to mention that some confusion for me is the lack of docs.

I also found the option `--no-daemon` to turn the warning off. The issue though is that the process identified in turbo.pid doesn't exist. Not running. So, maybe it tries to launch a daemon and can't?

>     * Can you tell me more about your OS?

Edition	Windows 10 Pro for Workstations
Version	21H2
Installed on	‎11/‎24/‎2021
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0



>     * Can you identify if you have write permissions to the path generated here? https://github.com/vercel/turborepo/blob/0dfa8e681c64a2bba9e8227d349b87f2f4bf7d04/cli/internal/daemon/daemon.go#L47
>        (we need better logging here to make this easier, you'd need to identify where Golang tempdir is creating a folder)

`%HOME%\AppData\Local\Temp` full permission. Also turbo creates a turbod folder there and turbod.pid and turbod.sock.

>     * what permissions does your user have?￼

I am fairly certain I have full permission. I run other go executables and go tools without issue.

**Comment by ringoz** [comment]
the same warning here on Windows 11

**Comment by gsoltis** [comment]
`turbo daemon status` should give a location for logs from the daemon. If you could post those, it would be helpful to figure out why the daemon is not running for is unable to be contacted.

**Comment by jayg-hive** [comment]
Hi there, also getting the same issue. On trying `turbo daemon status` I get this:
```
❯ pnpm exec turbo daemon status
Failed to contact daemon: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /tmp/turbod/0f771c1e12c2b3b3/turbod.pid is not running, and remove /tmp/turbod/0f771c1e12c2b3b3/turbod.pid
        - check the logs at /home/jayg-hive/.local/share/turborepo/logs/0f771c1e12c2b3b3-Prosper-Ultimate.log
        - the unix domain socket at /tmp/turbod/0f771c1e12c2b3b3/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

I'm on WSL2 with the following details:
```
WSL version: 0.67.6.0
Kernel version: 5.15.62.1
WSLg version: 1.0.44
MSRDC version: 1.2.3401
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.601
```

Nothing out of the ordinary on the logs, they just say something about `fsnotify` events on my monorepo files:
```
2022-09-23T09:27:16.339+0800 [DEBUG] turbod.rpc server.GlobWatcher: Got fsnotify event {/home/jayg-hive/hive-gaming/**redacted**/packages/utils/.turbo/turbo-test.log 3}
```

**Comment by MariuzMM** [comment]
Same issue for me on Mac, today installed turbo for first time

**Comment by gkn** [comment]
Gets the same warning message as @MariuzMM and @jayg-hive

Been using turbo for a while now. This warning started in version 1.5.2

On Windows10:

2022-09-23T14:16:10.471+0200 [ERROR] turbod: error: EXTRA_VALUE_AT_END="failed to lock the pid file at . Is another turbo daemon running?: Locked by other process"

No error on WSL2/Ubuntu :)

**Comment by himerus** [comment]
I'm seeing the same after a sweeping upgrade of dependencies today. Log output is a repeat of:

```
2022-09-23T09:42:53.645-0400 [ERROR] turbod: error: EXTRA_VALUE_AT_END="watching /Volumes/Work/code/MYPROJECT: timed out waiting for initial fsevents cookie: filewatching failed to start"
```

Console is outputting: 

```
yarn turbo daemon status
yarn run v1.22.19
$ /Volumes/Work/code/MYPROJECT/node_modules/.bin/turbo daemon status
Failed to contact daemon: the daemon is not running
✨  Done in 0.32s.
```

**Comment by gsoltis** [comment]
Couple things going on:
 - Minor, display-only bug related to `EXTRA_VALUE_AT_END`. I'll fix it, but that part is safe to ignore
 - re: cookie timeouts, I'm going to bump it a little, but if it takes too long, it's likely better to for us skip filewatching.
 - on that topic, the warning should be downgraded to informational. Filewatching is an optional optimization, and is not necessary for the proper functioning of `turbo`.
 
For those of you hitting the warning, can you confirm that `turbo` is still producing the correct results, just with the extra warning? Or is this actively breaking anyone? If so, I'd like to prioritize addressing breakage.

**Comment by gsoltis** [comment]
@gkn if you run `turbo daemon status`, it should give you the path to the `.pid` file? Can you check if there is in fact a process with that PID? Anything in the daemon logs (also from `turbo daemon status`) ?

**Comment by richardtorres314** [comment]
Running MacOS 12.6 here. When running the command `turbo daemon status`, I get "Failed to contact daemon: the daemon is not running." It's not preventing building for me, just giving the warning.

**Comment by gsoltis** [comment]
Addressing `EXTRA_VALUE_AT_END`: #2068

**Comment by gsoltis** [comment]
Additional context and debugging thoughts:
 - `turbo daemon status` is not intended to start the daemon. If it's not running, that's the status and that's fine. The daemon also does not stay alive forever, it has an idle timeout. The `turbo` cli will attempt to restart it next time it needs it.
 - running `turbo daemon` in your monorepo root will run the daemon in the foreground and log to the terminal.
 - There are some additional daemon-management commands: restart, start, and stop. See `turbo daemon --help`

Also, to everyone, thanks for your patience while we iron out the edge cases on this. There may be platforms and scenarios where the daemon does not work or does not provide benefit, and we'll work to detect those and behave accordingly as we identify them.

**Comment by AddictArts** [comment]
Hopefully this will help. I run the daemon and no errors to the console etc. Looks good using `turbo daemon`.

When I run `turbo run dev` the turbod dies. Last log message is
`2022-09-23T14:04:32.896-0700 [DEBUG] turbod.rpc server.GlobWatcher: Got fsnotify event {oranges\apps\web\.turbo\turbo-lint.log451477266 4}`

**Comment by jayg-hive** [comment]
> Couple things going on:
> 
> * Minor, display-only bug related to `EXTRA_VALUE_AT_END`. I'll fix it, but that part is safe to ignore
> * re: cookie timeouts, I'm going to bump it a little, but if it takes too long, it's likely better to for us skip filewatching.
> * on that topic, the warning should be downgraded to informational. Filewatching is an optional optimization, and is not necessary for the proper functioning of `turbo`.
> 
> For those of you hitting the warning, can you confirm that `turbo` is still producing the correct results, just with the extra warning? Or is this actively breaking anyone? If so, I'd like to prioritize addressing breakage.

Yup, no breakage whatsoever. It still runs the intended task. 👍

**Comment by gkn** [comment]
On Windows 10: 
1) I cleared the logs and pid + cookie file and folders in the user folder.

I still get the same warning message but now get a log file without error messages, just a lot of fsnotify messages. It even includes folders that is not specified as part of npm workspaces. This seems odd and wasteful, especially since it will watch node_modules in that folder too:

2022-09-24T08:41:40.051+0200 [DEBUG] turbod.rpc server.fsnotify: watching directory C:\xxxx\tools\storybook\node_modules\@mrmlnc

Initial startup seems slow.

Monorepo is relatively large, a few hundred folders with roughly 5000 source files.

2. Tried manual start of turbod:
$ npx turbo daemon start
connection to turbo daemon process failed. Please ensure the following:
...
...

**Comment by gsoltis** [comment]
Turning down daemon logging: #2085 

@gkn Thanks for the details. Better scoping filewatching sounds like an area for improvement.

**Comment by mikecousins** [comment]
![image](https://user-images.githubusercontent.com/725614/192606251-93b366c0-5698-4b82-926c-efcfed887b0c.png)

**Comment by gsoltis** [comment]
The logging and `EXTRA_VALUE_AT_END` fixes are now available in `turbo@1.5.4-canary.0`

**Comment by klapec** [comment]
Same here, I'm running `turbo@1.5.4` on arm macos 12.5.1.

```
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /var/folders/ls/sq7g081s1g3cvtlz41qp8z2m0000gn/T/turbod/fe25f7293c19b4d8/turbod.pid is not running, and remove /var/folders/ls/sq7g081s1g3cvtlz41qp8z2m0000gn/T/turbod/fe25f7293c19b4d8/turbod.pid
        - check the logs at /Users/Andrzej_Klapec/Library/Application Support/turborepo/logs/fe25f7293c19b4d8-tui-frontend-monorepo.log
        - the unix domain socket at /var/folders/ls/sq7g081s1g3cvtlz41qp8z2m0000gn/T/turbod/fe25f7293c19b4d8/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

I ran `yarn upgrade-interactive --latest` to update turbo (previously I had it at 1.4.3) and ran the codemod `npx @turbo/codemod migrate-env-var-dependencies` which updated my `turbo.json` file and created a new `.turbo-cookie` file. Is the `.turbo-cookie` file necessary and should it be committed into the repository?

**Comment by unional** [comment]
Gets the same warning, and the log file is empty.

On Windows 11, turbo 1.5.4

**Comment by gsoltis** [comment]
@klapec the `.turbo-cookie` is not necessary, it is intended to be in the directory that turbo uses for config data, not your repository. Did it appear at the root of your repo? And was it created by the codemod?

**Comment by klapec** [comment]
@gsoltis Thanks for the response. It did appear at the root of my monorepo, I assume it was either created by upgrading turbo to 1.5.4 (postinstall?) or by the codemod. I haven't seen exactly when was it created, I noticed it when I was about to commit my changes to the repository.

**Comment by gsoltis** [comment]
@klapec got it. we're looking into how it could've ended up in that spot, but it's safe to delete. Sorry about that!

**Comment by gsoltis** [comment]
For the windows users in this thread: it looks like we have an issue somewhere between Go, windows support for `AF_UNIX`, and grpc. I'm tracking down the exact fix, but I expect that's the cause of being unable to use the daemon thus far

**Comment by gsoltis** [comment]
We've published `turbo@1.5.5` which disables the daemon on windows while we sort out the `AF_UNIX` socket issue. I expect it will be re-enabled soon, as we've identified the issue and are working on a mitigation.

For those curious about the nitty-gritty details: 
 1. The Go grpc dialer uses `url.Parse` to determine how to connect to a server
 2. Go, like many other platforms, requires that the `Path` portion of a url start with a leading `/`
 3. GRPC uses the `Path` portion of a url for the location to Dial when the network is `unix` / url scheme is `unix://`
 4. This doesn't work well on windows, where file paths do not start with a leading `/`
 5. This means that we are either sending in a url that fails to parse (no leading '/'), or a url that parses, but has an extra leading '/'.
 
 Not to worry though, we can patch it to do special handling on windows. Coming soon.

**Comment by gkn** [comment]
@gsoltis Tried out turbo@1.5.5 on both WSL2/Ubuntu and on the (disabled) Windows variant now. No noticeable issues - good work :)

If you have the time, could you please explain where we actually benefit from utilizing the daemon? I cannot say I notice any differences and could not find any documentation addressing that btw.

**Comment by fveauvy** [comment]
@gsoltis : after upgrading Turborepo to version 1.5.5 I still notice the same warning message on my Macbook Pro M1 (MacOS 12.5.1).

A `.turbo-cookie` file is created at the root of my project everytime I run a turbo command.

As already mentioned, the warning message is :

```
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /var/folders/33/3dflr1_x01b07gpkyb7qsxtc0000gp/T/turbod/ba68216b5b606bf5/turbod.pid is not running, and remove /var/folders/33/3dflr1_x01b07gpkyb7qsxtc0000gp/T/turbod/ba68216b5b606bf5/turbod.pid
        - check the logs at /Users/{user}/Library/Application Support/turborepo/logs/ba68216b5b606bf5-{project}.log
        - the unix domain socket at /var/folders/33/3dflr1_x01b07gpkyb7qsxtc0000gp/T/turbod/ba68216b5b606bf5/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

Note that I have no trouble whatsoever with my pipeline. Everything seems to work accordingly.

**Comment by gsoltis** [comment]
@gkn Absolutely, and I apologize it hasn't made it into the docs yet. 

The daemon is purely a performance optimization, and not at all necessary for correct functioning of `turbo`. The daemon gives `turbo` the ability to do some work ahead of time or after a `turbo run` without blocking the user. The first feature that it implements today is skipping cache restoration if the outputs haven't changed since the last time a task was run. The result is faster cache hits, since they don't incur any file I/O. Some of the next features that are coming include:
 - uploading to remote caching in the background so that `turbo run` doesn't need to wait for uploading 
 - calculation of hash keys in advance so that `turbo run` doesn't need to wait to calculate what has changed, again avoiding file I/O during the time that a user is waiting
 
Furthermore, the daemon has an idle timeout and is disabled automatically in environments that don't "look" like dev machines: terminal is not a tty, presence of some known CI environment variables, etc.

**Comment by gsoltis** [comment]
@fveauvy can you give an example of how you are invoking `turbo` when you see the `.turbo-cookie` file show up? We are looking into it, but so far have not managed to reproduce the issue.

cc @mehulkar

**Comment by mehulkar** [comment]
@fveauvy @klapec I've filed https://github.com/vercel/turborepo/issues/2134 for the `.turbo-cookie` issue. I'm not sure it's related to the daemon outputs. Please feel free to add any context/additional info about your cases there!

**Comment by gsoltis** [comment]
windows users following along, re-enabling the daemon and fixing addressing of the `AF_UNIX` socket: #2137

**Comment by gsoltis** [comment]
Mac users, @fveauvy @MariuzMM @klapec @richardtorres314 , if you don't mind sharing, how are you invoking `turbo`? Is it via `npx turbo ...` ? Is it in a script in `package.json`? If so, which package manager are you using? Some other means?

Any errors in the logs (location reported in the error message)? 

I know we have one report of a timeout waiting for a filesystem cookie, anything else?

**Comment by unional** [comment]
A small plug here: maybe you can consider using https://github.com/unional/fixture#command-testing or something similar.
It allows you to write command line based tests. 🍻

**Comment by fveauvy** [comment]
> @fveauvy can you give an example of how you are invoking `turbo` when you see the `.turbo-cookie` file show up? We are looking into it, but so far have not managed to reproduce the issue.
> 
> cc @mehulkar

I was planning to record a gif showing you the issue, and I noticed something important regarding this matter.

In my `package.json`, the command `yarn build` will run `turbo run build`. FYI, I use yarn@1.22.19.

When I ran `yarn build` in the integrated terminal in VSCode there wasn't any warning message, and the file `.turbo-cookie` wasn't created.

But if I run `yarn build` in a dedicated terminal (I tried with [hyper.js](https://hyper.is/) or in the default [Terminal](https://en.wikipedia.org/wiki/Terminal_(macOS)) of macOS) I can see the warning message and the `.turbo-cookie` is created in the root of my project.

**Comment by richardtorres314** [comment]
@gsoltis I have turbo 1.5.3 installed globally. I run my `dev` script from the root of my project which runs  `turbo run dev --parallel`.

I'm using npm v8.1.0.

I only receive a warning message

```
failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
	- the process identified by the pid in the file at /var/folders/1t/ps8q7_ys0gdf21b2hqdlzmf00000gn/T/turbod/b7bf2d52b7e43eff/turbod.pid is not running, and remove /var/folders/1t/ps8q7_ys0gdf21b2hqdlzmf00000gn/T/turbod/b7bf2d52b7e43eff/turbod.pid
	- check the logs at /Users/richardtorres/Library/Application Support/turborepo/logs/b7bf2d52b7e43eff-class-recipes.log
	- the unix domain socket at /var/folders/1t/ps8q7_ys0gdf21b2hqdlzmf00000gn/T/turbod/b7bf2d52b7e43eff/turbod.sock has been removed
	You can also run without the daemon process by passing --no-daemon
```

Everything else works fine for me as of right now.

**Comment by gsoltis** [comment]
@elvisplaza as a workaround, can you try passing `--no-daemon`. I'm also curious how you're invoking `turbo`. Do you have it globally installed or is it a dependency in your repository? Is it being invoked via a script from `package.json`?

Re: connection failure, I suspect that's something else happening, since the daemon does not bind `localhost`. Can you check your output to verify that your server is running and that there is not also some other error?

**Comment by kalvenschraut** [comment]
In my repo there is a dir that is git ignored and auto managed by a docker container. Turbo repo's daemon is trying to watch this directory and dieing since it is trying to watch it.

![image](https://user-images.githubusercontent.com/30308012/194983415-1fecd234-5894-4c01-8434-2c7502d8eb8c.png)


Can the turbo repo not try to watch any files that are git ignored? Or allow somewhere to specify that I don't want it watching specific files? At very least not die if permission issues occur?

**Comment by unional** [comment]
1.5.5 disables daemon on windows, but it still checks for daemon during run:

```
Failed to mark outputs as cached for @just-web/preferences#coverage: rpc error: code = Unknown desc = timed out waiting for cookie
```

It waste quite a bit of time:

```
 Tasks:    34 successful, 34 total
Cached:    34 cached, 34 total
  Time:    9.878s >>> FULL TURBO
```

with `--no-daemon`:

```
Tasks:    34 successful, 34 total
Cached:    34 cached, 34 total
  Time:    678ms >>> FULL TURBO
```

**Comment by gsoltis** [comment]
@unional That looks like the daemon was not actually disabled. That error message in particular comes from the daemon code. 

Can you share your platform information? Where this happened, and verify the `turbo --version`?

Also note that `1.5.6` adds the daemon back for windows and should properly connect over a unix domain socket.

**Comment by AddictArts** [comment]
> @unional That looks like the daemon was not actually disabled. That error message in particular comes from the daemon code.
> 
> Can you share your platform information? Where this happened, and verify the `turbo --version`?
> 
> Also note that `1.5.6` adds the daemon back for windows and should properly connect over a unix domain socket.

It fails still on Windows 10. No daemon and constant pestering WARNING message. Back to `--no-daemon`.

**Comment by gsoltis** [comment]
@AddictArts sorry to hear that, do you by any chance know the build # for the version of windows you're running? 

My understanding is that anything after [17063](https://blogs.windows.com/windows-insider/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/) should work, but if you have an older version we can look at better ways to detect support.

**Comment by unional** [comment]
The error is from 1.5.6

**Comment by pupupue** [comment]
verified version 1.5.6 via `pnpm turbo --version` encountering same daemon warning

win 10 OSbuild: 19044.2006

**Comment by AddictArts** [comment]
@gsoltis Above, you have other reports for Windows 11 and 10 of the daemon not working in 1.5.6 which unfortunately turned it back on.

Edition	Windows 10 Pro for Workstations
Version	21H2
Installed on	‎11/‎24/‎2021
OS build	19044.2130
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by nathanhammond** [comment]
@y'all: thank you very much for the reports and your patience as we're trying to sort through this.

The biggest problems we have with this will always be our ability to reproduce the issues. Once we know how to reproduce issues we are able to quickly resolve them.

To that end, we always have to review each of the following possible contributing factors:
- OS + Version
- `turbo` version.
- Shell (terminal, VS Code, cmd, powershell, wsl, msys, etc.)
- Repository contents and configuration.
- Other software possibly contributing to issues (e.g. Docker)
- Filesystem permissions.
- and more!

If you're finding this issue please include as much information as possible into your report.

The number of places we have to look for issues is the combinatoric set of all of those inputs. For some large portion of issues we will never be able to reproduce the exact environment and have to rely on detailed reports of behavior from users, and for those we're grateful. We wouldn't have shipped it if we didn't believe that we were close.

Our conditions for turning off the daemon in the future will be based upon, "is this preventing a correct build execution?" We've taken great pains to ensure that it does not interfere with correctness and because of that we do not expect to ever make it opt-in again.

With regards to the warning, it's an important part of:
- Messaging to users who may have had an intermittent issue with their daemon process to restart it.
- Being able to receive feedback and improve.

Since it doesn't interfere with correct operation of `turbo` we also won't be removing it. For those of you for whom the daemon regularly fails and the warning bothers you, you have the option of using `turbo` with `--no-daemon` which will, as a side effect, silence the warning.

If you're seeing this issue for the first time, please consider opening a new issue instead of tagging onto this one so that we're better able to focus the conversations on the particular issues you report. At this point we suspect that they're _very_ unlikely to be the same contributing factors as other people.

**Comment by nathanhammond** [comment]
A couple of bonus debugging steps. For anybody who gets this warning:
1. `turbo daemon status`
2. Check to see if the `.log` file, the `.pid` file and the `.sock` file exist. Include this information in your report.
3. Manually check to see if the process specified by the `pid` file is running. Include this information in your report.
4. Kill the process specified by the `.pid` file.
5. Remove the `.log` file, the `.pid` file, and the `.sock` file.

Then:
1. Run `turbo daemon start`. This reduces the number of variables we need to consider inside of the Turborepo codebase.
2. Include the output of this command in your report.
3. Run `turbo daemon status`. Include the output of this command in your report.
4. Check to see if the `.log` file, the `.pid` file and the `.sock` file exist. Include this information in your report.
5. Manually check to see if the process specified by the `.pid` file is running. Include this information in your report.
6. Grab the contents of the `.log` file and include this information in your report.

If this doesn't produce an error message (possible!) include that information in your report.

***

If you're willing, I will pair with anybody who is able to consistently reproduce a daemon issue and is willing to set up a Turborepo development environment on their machine. You can reach DM me (nathanhammond) on our Discord: https://turborepo.org/discord. This is the surest way to get a resolution.

I'm in UTC+8, so we'll probably go back and forth a bit before finding a time to pair. It'll likely also be multiple sessions unless you set up a development environment prior to our call. (This is not a prerequisite! I'll be happy to work with you on that process.)

Note that for those of you on Windows I _will_ be less familiar with your environment, so it'll be a little bit of banging rocks together until it works, but we'll get there.

**Comment by nathanhammond** [comment]
@kalvenschraut Can you tell me about the permissions on `appendonlydir`? And what OS you're on?

**Comment by nathanhammond** [comment]
@\everybody else: I _do not_ have enough information for me to begin to identify issues. Please collect information from my previous post and drop it in this issue or reach out on Discord so that I can help diagnose!

**Comment by nathanhammond** [comment]
@unional Yup, that will do it.

So far we have identified two issues:
- @kalvenschraut's redis `appendonlydir` has a set of permissions that prevent the watcher from doing the right thing.
- @unional's watching across Windows volumes appears to be an issue.

I'll come back to those in the next week.

**Comment by kalvenschraut** [comment]
> @\everybody else: I _do not_ have enough information for me to begin to identify issues. Please collect information from my previous post and drop it in this issue or reach out on Discord so that I can help diagnose!
<img width="315" alt="Screen Shot 2022-10-14 at 11 18 44 AM" src="https://user-images.githubusercontent.com/30308012/195894067-636e874d-3c37-4dba-8be9-2e1cfe406f92.png">
system is above. 

permissions on it below.
<img width="554" alt="Screen Shot 2022-10-14 at 11 20 41 AM" src="https://user-images.githubusercontent.com/30308012/195894327-d9c26725-a260-424c-a18e-ffaf2dadd571.png">

**Comment by mwdiaz** [comment]
I've identified what appears to be the issue in my case. Similar to what other MacOS users have reported earlier in this issue, I was unable to start the daemon both in my actual repo as well as a brand new one bootstrapped using `npx create-turbo@latest`. I get the `.turbo-cookie` file and the logs are full of `timed out waiting for initial fsevents cookie: filewatching failed to start` messages.

Thinking about what's special in my setup, I realized that perhaps the filesystem where I do my development could be the culprit. Due to issues I've run into in the past, I have a separate encrypted APFS volume that's configured to be case-sensitive and that is where I put all my git repos. As soon as I tested `npx create-turbo@latest` outside that volume, everything worked just fine.

- MacOS 12.6
- turbo 1.5.6
- iTerm2
- APFS (Case-sensitive, Encrypted)

![Disk Utility screenshot showing case sensitive APFS volume](https://user-images.githubusercontent.com/1158605/195904027-f73f9dda-9c91-4c06-87d2-723ec1bb5b07.png)

**Comment by HeavenlyEntity** [comment]
Hello fellow hackers!

The turbo repo is not allowing my dev server to start using turbo but I am able to start it manually via in the `apps/[appname]` folder. I am trying to run `turbo run dev:table-widget --parallel` which is referring to a CRA that is just `yarn start`. When I run that I get:

```shell
$ yarn run dev:table-widget
yarn run v1.22.10
$ turbo run dev:table-widget --parallel
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:                                                                                       
        - the process identified by the pid in the file at C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.pid is not running, and remove C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.pid
        - check the logs at C:\Users\devvvvin\AppData\Local\turborepo\logs\80bf74a1a94d651f-portalgen-app.log                                                                                                                      
        - the unix domain socket at C:\Users\devvvvin\AppData\Local\Temp\turbod\80bf74a1a94d651f\turbod.sock has been removed                                                                                                      
        You can also run without the daemon process by passing --no-daemon                                                                                                                                                       
 ERROR  run failed: error preparing engine: the given task has not been registered
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Yet when I run it with the `--no-daemon` flag I get:

```shell
$ yarn run dev:table-widget
yarn run v1.22.10
$ turbo run dev:table-widget --parallel --no-daemon
 ERROR  run failed: error preparing engine: the given task has not been registered
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am running version **1.5.1** of turbo on a windows 10 machine. Inside of a git bash terminal. If someone could let me know what's going on. This started happening after I had to delete the `node_modules` folder to fix issues with an `eslint` package

**Comment by nathanhammond** [comment]
@HeavenlyEntity the daemon is not your root cause issue. Your issue is this:

ERROR  run failed: error preparing engine: the given task has not been registered

Please file a new issue! (I'll be collapsing your note here and my response.)

**Comment by timkinnane** [comment]
I have the same issue on M1 macOS 12.6, Turbo v1.6.1. Project using pnpm.

`pnpm turbo run build`:

```
WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following
        - the process identified by the pid in the file at /var/folders/1c/90x6p2gj6y3c1sv4b1ylqqqh0000gq/T/turbod/844ff8aa8eb9699c/turbod.pid is not running, and remove /var/folders/1c/90x6p2gj6y3c1sv4b1ylqqqh0000gq/T/turbod/844ff8aa8eb9699c/turbod.pid
        - check the logs at /Users/tim-kinnane/Library/Application Support/turborepo/logs/844ff8aa8eb9699c-fiscal.log
        - the unix domain socket at /var/folders/1c/90x6p2gj6y3c1sv4b1ylqqqh0000gq/T/turbod/844ff8aa8eb9699c/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

log content:

```
2022-10-23T09:40:54.478+1100 [ERROR] turbod: error watching <my repo path>: timed out waiting for initial fsevents cookie: filewatching failed to start
```

---

`pnpm turbo daemon`:

```
turbod: error watching <MY REPO PATH>: timed out waiting for initial fsevents cookie: filewatching failed to start
```

`pnpm turbo daemon --start`:

No output

`pnpm turbo daemon status`:

```
Failed to contact daemon: the daemon is not running
```

---

New project `npx create-turbo@latest` + `pnpm run build` had same issues, also tried `pnpm turbo daemon start` same as above.

**Comment by Suniron** [comment]
Same error using yarn on a turborepo project hosted in **WSL2**.

**Comment by rscorer** [comment]
> @ nathanhammond, the hint from @mwdiaz helped me, but I found out that it's not because of the APFS with or without case-sensitive and encryption, but simply because I'm using an external hard drive. I have formatted my hard drive multiple times with different options and I always get the error. This does not happen on the internal hard drive. I have tried different SSD hard drives and also an HDD, always with the same result. I tried it on a MacBook Pro 2022 M1 Max, MacBook Pro 2019 i9 and MacBook Pro 2016 i7.

That would make me think it's a permissions error, I wonder if they need to grant turbod access to our external drives? (I'm encountering the exact same error as you, and also using an external SSD)

**Comment by alexsedeke** [comment]
> That would make me think it's a permissions error, I wonder if they need to grant turbod access to our external drives? (I'm encountering the exact same error as you, and also using an external SSD)

After several hours of googling and testing without success, I unfortunately didn't find anything that would prevent the execution on an external SSD. I also have some applications on the same SSD and run them with no problems. I rather think that `turbod` has a path problem. It may think it is on the root drive and expect certain files relative to it.

**Comment by martaver** [comment]
I'm also experiencing this error. Turbo daemon is unable to be started.
- MacOS Monterey 12.4 (M1 Max)
- turbo 1.6.1
- Kitty & VSCode Integration Terminal

I get the same warning as for everyone else on each build, and also whenever I try to start/restart the daemon.

```
> pnpm turbo daemon start
connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at /var/folders/x5/qmrnnzlx5vx9gs38lb48y3x00000gp/T/turbod/2d9d7c57faf8bffd/turbod.pid is not running, and remove /var/folders/x5/qmrnnzlx5vx9gs38lb48y3x00000gp/T/turbod/2d9d7c57faf8bffd/turbod.pid
        - check the logs at /Users/sebastian.nemeth/.local/share/turborepo/logs/2d9d7c57faf8bffd-core.log
        - the unix domain socket at /var/folders/x5/qmrnnzlx5vx9gs38lb48y3x00000gp/T/turbod/2d9d7c57faf8bffd/turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
```

Neither the pid file nor the socket exist. Log shows no activity since a few days ago.

**Comment by rdmchr** [comment]
Me too.

- Windows 10 Pro, Version: 21H2, Experience: Windows Feature Experience Pack 120.2212.4180.0
- turbo 1.6.1
- yarn 1.23.0-20220130.1630
- Powershell

The turbod.pid and turbod.sock do exist and running `yarn turbo daemon` does nothing.
I also tried using WSL with Ubuntu 20.04.4 LTS and that worked fine, but going back to Windows I encountered the error again.

**Comment by xairoo** [comment]
Same for me.

Windows 11 Pro / 22H2 / 22623.875
Using Ubuntu WSL.

**Comment by chungweileong94** [comment]
> @ nathanhammond, the hint from @mwdiaz helped me, but I found out that it's not because of the APFS with or without case-sensitive and encryption, but simply because I'm using an external hard drive. I have formatted my hard drive multiple times with different options and I always get the error. This does not happen on the internal hard drive. I have tried different SSD hard drives and also an HDD, always with the same result. I tried it on a MacBook Pro 2022 M1 Max, MacBook Pro 2019 i9 and MacBook Pro 2016 i7.

Yeah, I'm only getting this issue if the codebase is in an external drive. Once I move the codebase to the internal drive, everything works perfectly fine. And I tested on both Mac mini M1 & Mac min Intel i3.

**Comment by timkinnane** [comment]
My issue was not an external drive, but it is a second partition. For what it's worth.

**Comment by toniopelo** [comment]
I'm on `Ubuntu 22.04` and on `turbo@1.6.3`.
And I got the following:
```sh
$ yarn turbo daemon
2022-11-06T18:41:56.259+0100 [ERROR] turbod: error watching /home/***/Workspaces/***: failed adding watch to /home/***/Workspaces/***/ops/mounts/postgresql/data: permission denied
```
It happens because I have some volumes mounted on docker that are running with different `uid/gid` than my linux user, and turbo doesn't have the right to add watches on these files.
Could we just ignore these instead of failing the deamon?
This si actually not a big deal for me anyway, I'll just use `--no-daemon` for now, but if it ever helps pinpointing some issue...

**Comment by nkkky** [comment]
Issue seems to still exist here. I am on `Windows 10`  with `turbo v1.6.3.` 

>  WARNING: failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
>         - the process identified by the pid in the file at C:\Users\NKKKY-\AppData\Local\Temp\turbod\379f4566e20df9e6\turbod.pid is not running, and remove C:\Users\NKKKY-\AppData\Local\Temp\turbod\379f4566e20df9e6\turbod.pid

Running `turbo daemon` does nothing it seems and terminal stays empty.

**Comment by gamertike** [comment]
I am also experiencing this issue with v1.6.3. Is there any fix available yet?

**Comment by nasso** [comment]
I am experiencing this issue with v1.6.3 in a devcontainer on Windows 11 (WSL 2, Docker Engine v20.10.21). Basically everything works fine until I restart my container. Could it be because `/tmp` (containing `/tmp/turbod`) is not cleared?

**Comment by ivoilic** [comment]
Still seeing this with MacOS 13.0.1, pnpm, and Turbo 1.6.3.

Logs read: `[ERROR] turbod: error watching /Users/user/some-project timed out waiting for initial fsevents cookie: filewatching failed to start
`

**Comment by HQ92** [comment]
Seeing this issue on Windows 10 Pro 22H2 19045.2364, yarn 1.22.19 and Turbo ^1.6.3.

" Failed to check if we can skip restoring outputs for frontend#build: rpc error: code = Unknown desc = timed out waiting for cookie. Proceeding to check cache"

**Comment by aminya** [comment]
I am also facing the same issue on Windows. Here is some error I saw in the log file that might help:

```rs
2023-01-10T22:05:31.631-0800 [ERROR] turbod.rpc server.GlobWatcher: could not get relative path from D:\GitHub\JavaScrip
t\test to C:\Users\aminy\AppData\Local\turborepo\cookies\a51a5552e0f5de7f\13.cookie: Rel: can't make C:\U
sers\aminy\AppData\Local\turborepo\cookies\a51a5552e0f5de7f\13.cookie relative to D:\GitHub\JavaScript\test

```

**Comment by sandercoffee** [comment]
### Same error for me, Windows 11 Pro, 22H2, 22621.1105

 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\XXXXX\AppData\Local\Temp\turbod\022062e835c71c17\turbod.pid is not running, and remove C:\Users\XXXXX\AppData\Local\Temp\turbod\022062e835c71c17\turbod.pid
        - check the logs at C:\Users\XXXXX\AppData\Local\turborepo\logs\022062e835c71c17-XXXXX.log     
        - the unix domain socket at C:\Users\XXXXX\AppData\Local\Temp\turbod\022062e835c71c17\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
                
> If I run "pnpm turbo daemon" in root and keed it open, no erros apear

**Comment by clearly-outsane** [comment]
Got this on windows 10! No idea why

**Comment by RickRyan26** [comment]
Same. Windows 11 Home

**Comment by ImBIOS** [comment]
Same

```sh
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.04 GB / 7.65 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  npmPackages:
    turbo: latest => 1.8.2
```

**Comment by cuppachino** [comment]
Reposting here to consolidate. 

**Windows system assumed buffer larger than it is, events have likely been missed.**

`v1.8.2`


```md
2023-02-24T16:06:04.718-0600 [ERROR] turbod.rpc server.GlobWatcher: file watching received an error: Windows system assumed buffer larger than it is, events have likely been missed.
```

**Comment by i7eo** [comment]
Same issue on win10

**Comment by kemaldotearth** [comment]
Experiencing this issue on MacOS, ran a fresh `npm install` on a newly cloned repo and experienced the same thing.

Also had a `.turbo-cookie` generated in the root of my project. Is it okay to remove this?

**Comment by ambroselittle** [comment]
Same. My code is on APFS (Case-sensitive) non-primary partition.

Installed fresh today (trying turbo out):
`pnpm dlx create-turbo@latest` (trying default sample with pnpm)
`pnpm install turbo --global`

Turbo 1.8.3
node 18.15.0
pnpm 7.29.1
Mac 13.2.1 (22D68) (Apple Silicon)

Running `turbo hello` produces `WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed.`

The `.pid` it mentions does not exist. There is no `turbod` folder under the referenced temp folder.

Running `turbo daemon`:
`[ERROR] turbod: error watching /Volumes/Code/Repos/Org/my-repo: timed out waiting for initial fsevents cookie: filewatching failed to start
Turbo error: watching /Volumes/Code/Repos/Org/my-repo: timed out waiting for initial fsevents cookie: filewatching failed to start`

I see the same in the log file it mentions.

Running `turbo hello --no-daemon` seems to work fine.

**Comment by ImBIOS** [comment]
> Same
> 
> ```shell
> System:
>     OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
>     CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
>     Memory: 4.04 GB / 7.65 GB
>     Container: Yes
>     Shell: 5.8.1 - /usr/bin/zsh
>   Binaries:
>     Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
>     npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
>   npmPackages:
>     turbo: latest => 1.8.2
> ```

Now, it's solved in:

System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 33.84 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/4167_1678841791232/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/4167_1678841791232/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3

**Comment by boeckMt** [comment]
I got the same error using turbo only installed [per-repository](https://turbo.build/repo/docs/installing#install-per-repository) and not globally in version `1.7.4`.

After this I [installed turbo globally](https://turbo.build/repo/docs/installing#install-globally) and per-repository with version `1.8.6` and the error still exists. 

---

Then I tried removing the global installation of turbo `npm uninstall turbo -g` and the folders `C:\Users\...\AppData\Roaming\turborepo` and `C:\Users\...\AppData\Local\Temp\turbod` and reinstall it again, **and now it works in both ways** installed **per-repository** or **globally**.

---

### What package manager are you using?
npm

### What operating system are you using?
Windows

**Comment by dennis-gonzales** [comment]
able to replicate on windows 10 on my end also

**Comment by ph55** [comment]
Looks like permissions issue. I can start the daemon with `sudo`. Without the `sudo` - no success.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1386622/230792273-8179da13-6661-402c-8414-65f9645ee83a.png">

**Comment by philippmossier** [comment]
I was able to fix it by deleting `~/.local/share/turborepo`

**Comment by prodkt** [comment]
Just started happening here on MacOS and Windows machines. Seems this is actively being worked through though just confirming this is still happening as my time posting here.

**Comment by Muhammed-Alaa-Kanzari** [comment]
same thing is happening to me for the latest version 1.9.3 
I can't build my project because of this

**Comment by zoffyzhang** [comment]
> I was able to fix it by deleting `~/.local/share/turborepo`

works for win10 by deleting `C:\Users\zoffy\AppData\Local\Temp\turbod`, because some files were locked

**Comment by ivancuric** [comment]
Issue still present on MacOS 13.3.1 (a), running under pnpm 8.5.1

**Comment by ekqt** [comment]
Issue still present: MacOS 13.3.1 

```
 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
	- the process identified by the pid in the file at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid is not running, and remove /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid
	- check the logs at /Users/hectorsosa/Library/Application Support/turborepo/logs/25b12ed5a16fdb56-screenshot.log
	- the unix domain socket at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.sock has been removed
	You can also run without the daemon process by passing --no-daemon
```

**Comment by jahavej** [comment]
> Issue still present: MacOS 13.3.1
> 
> ```
>  WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
> 	- the process identified by the pid in the file at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid is not running, and remove /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.pid
> 	- check the logs at /Users/hectorsosa/Library/Application Support/turborepo/logs/25b12ed5a16fdb56-screenshot.log
> 	- the unix domain socket at /var/folders/k2/44m5w6m54p5bw93yvqn4flwh0000gn/T/turbod/25b12ed5a16fdb56/turbod.sock has been removed
> 	You can also run without the daemon process by passing --no-daemon
> ```

I just resolved it by running `turbo daemon status` and `turbo daemon restart` (or `turbo daemon run` if the daemon is not running) -- macOS 13.3.1 (a)

**Comment by ivancuric** [comment]
I believe this is triggered when upgrading the turbo local dependency. I haven't had any success using the npx codemod, and upgrading it via `pnpm` locally still shows the codemod upgrade banner notification.

**Comment by Icoder9699** [comment]
Hello everyone! I just deleted the file that showed in the warn 
example: _C:\Users\AKARIM~1\AppData\Local\Temp\turbod\4800a0aaaf98de35\turbod.pid_

**Comment by Tarrowren** [comment]
If you run `npx turbo daemon start`, everything is fine.

If you run `turbo run lint` let it start the daemon on its own, the daemon exits within a few seconds of finishing and the pid file is not cleaned up.

**Comment by ivancuric** [comment]
> @ekqt I just resolved it by running `turbo daemon status` and `turbo daemon restart` (or `turbo daemon run` if the daemon is not running) -- macOS 13.3.1 (a)

Getting the error `ERROR unable to connect: unable to make handshake: bad grpc status code: Operation is not implemented or not supported` for first 2 commands, and `unrecognized subcommand 'run'` for third.

**Comment by homer0** [comment]
I updated to `1.9.9` a couple of hours ago and started to see this issue. When trying to run the `status` command, I got the same message as @ivancuric: `ERROR unable to connect: unable to make handshake: bad grpc status code: Operation is not implemented or not supported`.

I first tried getting the process from the `turbod.pid` and `kill`ing it, but that didn't work, so I just deleted the `turbod` directory, called `pnpm exec turbo daemon start` (not `restart`, which throws because it's not running) and now is working 😀. Not sure if it was the right move tho :P

**Comment by cp-Coder** [comment]
> Hello everyone! I just deleted the file that showed in the warn example: _C:\Users\AKARIM~1\AppData\Local\Temp\turbod\4800a0aaaf98de35\turbod.pid_ and it helped

I was also getting the error. By following the above instructions, I deleted the temp files in turbod directory. Now there is no error while using turbo

**Comment by ZeldOcarina** [comment]
If I try to clean and start the daemon I get:

```
cat: /var/folders/6x/px3zsgnn2rnbwmdmn3czfnym0000gn/T/turbod/027bccfcf592b126/turbod.pid: No such file or directory
% turbo daemon clean
Done
% turbo daemon clean
Done
% turbo daemon start
% turbo daemon status
ERROR unable to connect: daemon is not running
```

**Comment by the-baaron** [comment]
Same here :( 

> If I try to clean and start the daemon I get:
> 
> ```
> cat: /var/folders/6x/px3zsgnn2rnbwmdmn3czfnym0000gn/T/turbod/027bccfcf592b126/turbod.pid: No such file or directory
> % turbo daemon clean
> Done
> % turbo daemon clean
> Done
> % turbo daemon start
> % turbo daemon status
> ERROR unable to connect: daemon is not running
> ```

**Comment by hellovai** [comment]
> Same here, on MacOS (M2)
> 
> > If I try to clean and start the daemon I get:
> > ```
> > cat: /var/folders/6x/px3zsgnn2rnbwmdmn3czfnym0000gn/T/turbod/027bccfcf592b126/turbod.pid: No such file or directory
> > % turbo daemon clean
> > Done
> > % turbo daemon clean
> > Done
> > % turbo daemon start
> > % turbo daemon status
> > ERROR unable to connect: daemon is not running
> > ```

I'm getting the exact same response

**Comment by jfrconley** [comment]
> > Same here, on MacOS (M2)
> > > If I try to clean and start the daemon I get:
> > > ```
> > > cat: /var/folders/6x/px3zsgnn2rnbwmdmn3czfnym0000gn/T/turbod/027bccfcf592b126/turbod.pid: No such file or directory
> > > % turbo daemon clean
> > > Done
> > > % turbo daemon clean
> > > Done
> > > % turbo daemon start
> > > % turbo daemon status
> > > ERROR unable to connect: daemon is not running
> > > ```
> 
> I'm getting the exact same response

Also same

**Comment by aidenberzins** [comment]
> > > Same here, on MacOS (M2)
> > > > If I try to clean and start the daemon I get:
> > > > ```
> > > > cat: /var/folders/6x/px3zsgnn2rnbwmdmn3czfnym0000gn/T/turbod/027bccfcf592b126/turbod.pid: No such file or directory
> > > > % turbo daemon clean
> > > > Done
> > > > % turbo daemon clean
> > > > Done
> > > > % turbo daemon start
> > > > % turbo daemon status
> > > > ERROR unable to connect: daemon is not running
> > > > ```
> > 
> > 
> > I'm getting the exact same response
> 
> Also same

+1 as well

**Comment by bengrunfeld** [comment]
One of the guys on my team solved this by deleting his package-lock.json and running the install again. That was what worked for him.

**Comment by chungweileong94** [comment]
> One of the guys on my team solved this by deleting his package-lock.json and running the install again. That was what worked for him.

Delete lock file and reinstall could potentially break your application tho.

**Comment by GerroDen** [comment]
Since today i get that error regularly with v1.10.7
There has been no issue before today.

**Comment by arlyon** [comment]
Hello folks, we have been shipping a host of daemon improvements (including a total rewrite) over the last year or so, so while I am not promising there are no issues, the set of issues that you can hit are completely different and I think that warrants opening a new ticket for the new daemon, since it is hard to filter in this thread between current problems and ones affecting the old implementation. Thank you all for chiming in and helping make turbo better, and don't hesitate to open a new issue if you are still having issues post 1.11.
