### ISSUE TITLE
[turborepo] Error while trying to run script with filter when filter eliminates all possible workspaces

### ISSUE THREAD

**Issue by trappar** [vercel/turbo#3918]
### What version of Turborepo are you using?

1.8.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

In my project, if I'm sitting in the main branch with a clean working copy and I try to run:
```
turbo --filter "[main]" lint
```
I get the following output
```
• Packages in scope: 
• Running lint in 0 packages
• Remote caching disabled

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    66ms 
```

However, if I make a modification to a file in my monorepo's root that is not inside a specific package, and is not an input to any package, such as `.gitignore`, then I get the following output:
```
 ERROR  run failed: error preparing engine: Could not find the following tasks in project: lint
Turbo error: error preparing engine: Could not find the following tasks in project: lint
```

### Expected Behavior

I should not be getting this error, and turbo should instead simply run no tasks.

### To Reproduce

In a monorepo with turborepo, checkout main/master with a clean working copy, then modify the project's `.gitignore` and try running `turbo --filter "[{branch}]" {script}` where `{branch}` is your main/master branch and `{script}` is any script configured in the `turbo.json` pipelines.

I just tested and this can be replicated using the starter monorepo created via `npx create-turbo@latest`

**Comment by tknickman** [comment]
Hey @trappar, this should be fixed in 1.8.2 (released today)!

**Comment by trappar** [comment]
Oops, sorry I was mistaken in the bug report. I'm actually already on 1.8.2, and it's still occurring. I'll update my original issue to reflect that.

**Comment by trappar** [comment]
@tknickman could you please reopen? 😅

**Comment by tknickman** [comment]
Ah, my fault @trappar, sorry about that. We'll take a look.

**Comment by vladi-strilets** [comment]
similar issue, using 1.8.2

**Comment by tkstang** [comment]
I am experiencing this issue as well. Thanks for taking a look!

**Comment by mehulkar** [comment]
Thanks for the reporting @trappar and @tkstang! I was able to reproduce and the fix issue in #3951. We should hopefully get a new patch release out shortly! The explanation for the bug is essentially the same as in https://github.com/vercel/turbo/issues/3896#issuecomment-1439193366. Apologies for the inconvenience!

**Comment by mehulkar** [comment]
Just an update: we released 1.8.3 with the fix: https://github.com/vercel/turbo/releases/tag/v1.8.3

**Comment by Tittoh** [comment]
I just created a new project and quick search on a similar error brought me here.
```
run failed: error preparing engine: Could not find the following tasks in project: hello
Turbo error: error preparing engine: Could not find the following tasks in project: hello
```
according to the docs, [Understanding `turbo.json`](https://turbo.build/repo/docs/getting-started/create-new#3-understanding-turbojson) the expected error is:
```
task `hello` not found in turbo `pipeline` in "turbo.json".
Are you sure you added it?
```
`dev`, `lint` and `build commands are working as expected.

`v: 1.8.3`

**Comment by mehulkar** [comment]
@Tittoh good catch. Could you file a new issue to update the docs? If you don’t get to it I’ll make a note to do this on Monday! The error message did indeed change

**Comment by arantespp** [comment]
I got this error with `v: 1.8.3` and running lint from root (`//#lint`). My [`turbo.json` config](https://github.com/ttoss/ttoss/blob/main/turbo.json). 

![image](https://user-images.githubusercontent.com/16626980/223773167-14cd048a-0029-4aaa-b19c-a9590646acac.png)

**Comment by nathanhammond** [comment]
@arantespp `//#lint` is how to address that root task.

**Comment by arantespp** [comment]
It's working now! It didn't work if I updated manually (`yarn add -DW turbo`), but it worked when I updated via codemod (`npx @turbo/codemod update`).

**Comment by rhkdgns95** [comment]
This issue can be resolved by downgrading the version to 1.10.4.

It's not an ideal solution.

**Comment by magicspon** [comment]
I'm seeing this issue as well

yarn lint - works
turbo run link - works

but when either task is run via [lint-staged](https://github.com/lint-staged/lint-staged) i get:

```
✖ turbo run lint:
 ERROR  run failed: error preparing engine: Could not find the following tasks in project: _path_to_repo_/.lintstagedrc.js, _path_to_repo/apps/cms/src/globals/Seo.ts, _path_to_repo/apps/cms/src/seed.ts, _path_to_repo/apps/cms/src/singles/About.ts, _path_to_repo/apps/cms/src/singles/Home.ts, _path_to_repo/apps/web/src/app/page.tsx, _path_to_repo/packages/config/eslint/react-internal.js, _path_to_repo/packages/ui/index.tsx
```

repo: https://github.com/magicspon/next-payloadcms-mono

**Comment by mehulkar** [comment]
@magicspon since this is already closed a long time ago, can you please open a new issue (thanks for the repro!)

**Comment by magicspon** [comment]
@mehulkar done ->  https://github.com/vercel/turbo/issues/6358
