### ISSUE TITLE
[turbopack] [tailwind] warnings and slow build time with tailwind

### ISSUE THREAD

**Issue by Soraka-TheBanshee** [vercel/turbo#3972]
### What version of Turbopack are you using?

alpha

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Windows

### Describe the Bug

Hello. I'm trying to use Turbopack with Tailwind.
I execute next dev --turbo --show-all,
and after i open localhost:3000 on my browser im getting those errors:

```
warning - [parse]
  node_modules\postcss\lib\input.js
    node_modules\postcss\lib\input.js:44:20  lint TP1006 path.resolve(???*0*) is very dynamic
        40 |         isAbsolute(opts.from)
        41 |       ) {
        42 |         this.file = opts.from
        43 |       } else {
           |                     v
        44 +         this.file = resolve(opts.from)
           |                     ^
        45 |       }
        46 |     }
        47 | 
        48 |     if (pathAvailable && sourceMapAvailable) {
    
    - *0* ???*1*["from"]
      ⚠️  unknown object
    - *1* opts
      ⚠️  pattern without value

  node_modules\postcss\lib\previous-map.js
    node_modules\postcss\lib\previous-map.js:88:8  lint TP1004 fs.existsSync(???*0*) is very dynamic
        84 |   }
        85 | 
        86 |   loadFile(path) {
        87 |     this.root = dirname(path)
           |         v
        88 +     if (existsSync(path)) {
           |         ^
        89 |       this.mapFile = path
        90 |       return readFileSync(path, 'utf-8').toString().trim()
        91 |     }
        92 |   }
    
    - *0* arguments[0]
      ⚠️  function calls are not analysed yet

    node_modules\postcss\lib\previous-map.js:90:13  lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
        86 |   loadFile(path) {
        87 |     this.root = dirname(path)
        88 |     if (existsSync(path)) {
        89 |       this.mapFile = path
           |              v
        90 +       return readFileSync(path, 'utf-8').toString().trim()
           |              ^
        91 |     }
        92 |   }
        93 |
        94 |   loadMap(file, prev) {
    
    - *0* arguments[0]
      ⚠️  function calls are not analysed yet
```

Couldn't find anything about it.

Im new to those techs, and i'm sorry if i've just done something wrong

### Expected Behavior

Expected fast build and no warnings.

### To Reproduce

I just followed instructions on https://tailwindcss.com/docs/guides/nextjs

### Reproduction Repo

https://github.com/Soraka-TheBanshee/imdb-clone

**Comment by GrantMLambert** [comment]
This seems to be an issue with Next@13.2...Downgrading to Next@13.1.6 fixed this issue for me.

**Comment by Soraka-TheBanshee** [comment]
> This seems to be an issue with Next@13.2...Downgrading to Next@13.1.6 fixed this issue for me.

Oh, am not alone

**Comment by Soraka-TheBanshee** [comment]
Hmm, still error after downgrade, but works faster. Maybe i just downgraded it in a wrong way, huh

**Comment by dgrichevsky** [comment]
I have the same issue

**Comment by kkhys** [comment]
I use pnpm for package management and have had same problems.
Here is the project I am creating with next13.
https://github.com/kkhys/me/tree/30338efc136064b7991d16c31ecff2458d6cce15

**Comment by maskovlad** [comment]
I have the same problems. Next13.2.3-Turbopack-Tailwind. Everything works fine with Webpack.

**Comment by blackevn** [comment]
> This seems to be an issue with Next@13.2...Downgrading to Next@13.1.6 fixed this issue for me.

Worked for me

**Comment by davletovalmir** [comment]
>  This seems to be an issue with Next@13.2...Downgrading to Next@13.1.6 fixed this issue for me.

Worked for me too

**Comment by Tunakirkoc** [comment]
Same for me with Next@13.2.4 and tailwindcss@3.2.7

**Comment by padmaia** [comment]
The warnings should no longer display by default in the latest canary. @Soraka-TheBanshee When say the build time is slow, what are you experiencing?

**Comment by GrantMLambert** [comment]
I am receiving these errors when attempting to use turbopack under the Next 13.2.5-canary.13

warning - [parse]
  node_modules\postcss\lib\input.js
    node_modules\postcss\lib\input.js:44:20  lint TP1006 path.resolve(???*0*) is very dynamic
        40 |         isAbsolute(opts.from)
        41 |       ) {
        42 |         this.file = opts.from
        43 |       } else {
           |                     v
        44 +         this.file = resolve(opts.from)
           |                     ^
        45 |       }
        46 |     }
        47 | 
        48 |     if (pathAvailable && sourceMapAvailable) {

    - *0* ???*1*["from"]
      ⚠️  unknown object
    - *1* opts
      ⚠️  pattern without value

  node_modules\postcss\lib\previous-map.js
    node_modules\postcss\lib\previous-map.js:88:8  lint TP1004 fs.existsSync(???*0*) is very dynamic
        84 |   }
        85 | 
        86 |   loadFile(path) {
        87 |     this.root = dirname(path)
           |         v
        88 +     if (existsSync(path)) {
           |         ^
        89 |       this.mapFile = path
        90 |       return readFileSync(path, 'utf-8').toString().trim()
        91 |     }
        92 |   }
    
    - *0* arguments[0]
      ⚠️  function calls are not analysed yet

    node_modules\postcss\lib\previous-map.js:90:13  lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
        86 |   loadFile(path) {
        87 |     this.root = dirname(path)
        88 |     if (existsSync(path)) {
        89 |       this.mapFile = path
           |              v
        90 +       return readFileSync(path, 'utf-8').toString().trim()
           |              ^
        91 |     }
        92 |   }
        93 |
        94 |   loadMap(file, prev) {

    - *0* arguments[0]
      ⚠️  function calls are not analysed yet

warning - [analyze]
  node_modules\@react-spring\types\animated.js
    unexpected export *
    export * used with module [project]/node_modules/@react-spring/types/animated.js (ecmascript) which has no exports
    Typescript only: Did you want to export only types with `export type { ... } from "..."`?

  node_modules\@react-spring\types\interpolation.js
    unexpected export *
    export * used with module [project]/node_modules/@react-spring/types/interpolation.js (ecmascript) which has no exports
    Typescript only: Did you want to export only types with `export type { ... } from "..."`?
    
    
    
Unhandled errors that happened during execution of application code.
1 of 1 
Error: Failed to load chunk _next/static/chunks/node_modules_react-icons_gi_index.esm_8f1fce.js from module [next]/entry/app/hydrate.tsx/(PAGE)/[project]/app/page.tsx (ecmascript) (ecmascript)

**Comment by cleversonffaria** [comment]
Downgrading to next 13.1.6 worked for me.

**Comment by Mesapholis** [comment]
I'd really like to not downgrade, as I am using the new routing feature under Next 13.2
Is there a way to disable the warning to not show in the browser?

**Comment by shriekdj** [comment]
> I'd really like to not downgrade, as I am using the new routing feature under Next 13.2 Is there a way to disable the warning to not show in the browser?

how

**Comment by shriekdj** [comment]
my issue resolved after i updated versions of packages like next to canary version `next@canary` and also upgrading `postcss@latest` and my issue resolved

**Comment by shriekdj** [comment]
This issue is related to linters of turborepo.
add this texts in file named `postcss.config.js`
`/* eslint-disable */` at start of file and `/* eslint-enable */` at the end of file.

my file looked like this
```javascript
/* eslint-disable */
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
/* eslint-enable */
```

**Comment by omer-os** [comment]
**hi**

did you solve the problem ?

im getting this error :

`Turbopack compiled with warnings
1 of 4 
lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
warning - [parse] [project]/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/previous-map.js  /node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/previous-map.js:90:13  lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
      86 |   loadFile(path) {
      87 |     this.root = dirname(path)
      88 |     if (existsSync(path)) {
      89 |       this.mapFile = path
         |              v
      90 +       return readFileSync(path, 'utf-8').toString().trim()
         |              ^
      91 |     }
      92 |   }
      93 | 
      94 |   loadMap(file, prev) {
  
  - *0* arguments[0]
    ⚠️  function calls are not analysed yet
`

**Comment by shriekdj** [comment]
> **hi**
> 
> did you solve the problem ?
> 
> im getting this error :
> 
> ```
> Turbopack compiled with warnings
> 1 of 4 
> lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
> warning - [parse] [project]/node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/previous-map.js  /node_modules/.pnpm/postcss@8.4.21/node_modules/postcss/lib/previous-map.js:90:13  lint TP1004 fs.readFileSync(???*0*, "utf-8") is very dynamic
>       86 |   loadFile(path) {
>       87 |     this.root = dirname(path)
>       88 |     if (existsSync(path)) {
>       89 |       this.mapFile = path
>          |              v
>       90 +       return readFileSync(path, 'utf-8').toString().trim()
>          |              ^
>       91 |     }
>       92 |   }
>       93 | 
>       94 |   loadMap(file, prev) {
>   
>   - *0* arguments[0]
>     ⚠️  function calls are not analysed yet
> ```

yeah i got the same issue and it's resolved by updating the `postcss.config.js` as per https://github.com/vercel/turbo/issues/3972#issuecomment-1499396061

**Comment by iRevolutionDev** [comment]
Same issues, more than 7 seconds to compile route (i'm using turbopack, mui and tailwind)

problem in next.js 13.2.6 and 13.3
![image](https://user-images.githubusercontent.com/39312595/232177674-afc15da1-24d7-4002-a17b-d3f541962b4c.png)

**Comment by Maverick17user** [comment]
Still an issue

next - 13.4.3
react - 18.2.0

<details>

<summary>Issue 1 </summary>

<img width="1109" alt="image" src="https://github.com/vercel/turbo/assets/30416868/e3ea7a79-14f0-4bbb-83bf-967fee4bd566">

</details>

<details>

<summary>Issue 2</summary>

<img width="1064" alt="image" src="https://github.com/vercel/turbo/assets/30416868/65135764-7cd2-41c1-a1d1-162c7b2940f8">

</details>

**Comment by MrOxMasTer** [comment]
![image](https://github.com/vercel/turbo/assets/59291123/70c7e63f-1909-4bce-a044-0808bf00af4a)

"eslint": "^8.42.0",
"eslint-config-next": "13.4.4",
"next": "^13.4.5-canary.9",
"postcss": "^8.4.24",

The problem persists

**Comment by timneutkens** [comment]
Going to close this as Tailwindcss is supported now and the related tests are passing, if you're still running into problems please open a new issue with a reproduction. Thanks!

**Comment by thiagobarbosa** [comment]
I had that problem with readFile, and it worked after changing from this:

`const fileString = await fs.readFile(filePath, 'utf8');`

to this:

```
const absolutePath = path.join(process.cwd(), filePath);
const fileString = await fs.readFile(absolutePath, 'utf8');
```

**Comment by neslob** [comment]
Thanks @thiagobarbosa 👍 

Adding `const absolutePath = path.join(process.cwd(), filePath);` solved my issue.
