### ISSUE TITLE
[turbopack] Error resolving commonjs request

### ISSUE THREAD

**Issue by RigottiG** [vercel/turbo#4282]
### What version of Turborepo are you using?

none

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Mac

### Describe the Bug

After upgrading my Next 12 to 13, when I build the app with the --turbo flag I get some errors in node_modules libs.

eg: 
![image](https://user-images.githubusercontent.com/13246770/226601202-8154337f-9301-4fdd-a244-91ad33ea9f96.png)

### Expected Behavior

build without errors

### To Reproduce

1. upgrade Next to 13
2. run `pnpm dev --turbo`

**Comment by padmaia** [comment]
We're aware of this issue and plan to fix, but you should be able to dismiss this error and use the app just fine from what we've seen. This is happening because `utf-8-validate` is a transitive devDependency and is required in a `try` block and we don't handle that correctly yet.

**Comment by padmaia** [comment]
Should be resolved with Next.js 13.3.0

**Comment by godfrednanaowusu** [comment]
unfortunately its still there even with 13.3.2 and the canary.13

**Comment by mjad218** [comment]
@padmaia  I am still getting this error after updating to next @13.4.13. 

I am using TurpoPack and TurpoRepo

**Comment by mjad218** [comment]
```
Errors reported when compiling the application.
The application might work partially, but that's unlikely.
1 of 1 
Error resolving commonjs request
error - [resolve] [project]/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js  /node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:540:22  Error resolving commonjs request
     536 |         + "});"
     537 |         + (data ? "req.write('" + JSON.stringify(data).slice(1,-1).replace(/'/g, "\\'") + "');":"")
     538 |         + "req.end();";
     539 |       // Start the other Node Process, executing this string
         +                       v----------------------------------------v
     540 +       var syncProc = spawn(process.argv[0], ["-e", execString]);
         +                       ^----------------------------------------^
     541 |       var statusText;
     542 |       while(fs.existsSync(syncFile)) {
     543 |         // Wait while the sync file is empty
     544 |       }
  
  unable to resolve module "-e" or dynamic
  
  | It was not possible to find the requested file.
  | Parsed request as written in source code: module "-e" or dynamic
  | Path where resolving has started: [project]/node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js
  | Type of request: commonjs request
  | Import map: No import map entry
  | 
```

**Comment by wwwhatley** [comment]
Why was this closed? Clearly it hasn't been resolved... still persisting on Next 14

**Comment by joacub** [comment]
This still been a problem

**Comment by padmaia** [comment]
If you are still experiencing this issue, can you please open an issue in the Next.js repo with a reproduction 🙏

**Comment by wwwhatley** [comment]
@padmaia why? This wasn't resolved in the first place, as you can clearly see from the comments above.
