### ISSUE TITLE
Turbopack throws warnings related to dynamic function calls when using PostCSS

### ISSUE THREAD

**Issue by etarley** [vercel/turbo#4301]
### What version of Turbopack are you using?

Turbopack Nightly Release turbopack-230307.2

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Linux

### Describe the Bug

 When I use PostCSS with Turbopack, I encounter three warnings in the Turbopack log. These warnings are related to dynamic function calls in the PostCSS package.

The three warnings are as follows:

1. TP1004 fs.existsSync(???0) is very dynamic
File: [project]/node_modules/postcss/lib/previous-map.js
Line: 88
 
2. TP1004 fs.readFileSync(???0, "utf-8") is very dynamic
File: [project]/node_modules/postcss/lib/previous-map.js
Line: 90
 
3. TP1006 path.resolve(???0) is very dynamic
File: [project]/node_modules/postcss/lib/input.js
Line: 44

### Expected Behavior

Turbopack should not throw warnings related to dynamic function calls when using PostCSS.

### To Reproduce

1. Install and configure Turbopack and PostCSS.
2. Run the bundling process with Turbopack.
3. Observe the warnings in the Turbopack log related to dynamic function calls in PostCS

### Reproduction Repo

https://github.com/etarley/reddit_clone

**Comment by padmaia** [comment]
This is resolved in the latest canary, will close when it's available in the next patch

**Comment by padmaia** [comment]
Should no longer be an issue in 13.3.0

**Comment by sfedorov-at-wiley** [comment]
I still get this warnings

<img width="972" alt="image" src="https://github.com/vercel/turbo/assets/83008702/c75f4b50-217b-4284-8051-b6093ef9568a">
